### PR TITLE
HIP Texture Support

### PR DESCRIPTION
**Pull request by weixingzhang**

### CODE REVIEW

**Comment by whchung** [comment]
@weixingzhang Thanks for this very important contribution. Before @mangupta reviews this PR, I have some general questions:

1. could you provide an overview of what's achieved in this PR? what's implemented and what's not?
1. there is no tests associated in this PR. please help amend it by supplying tests.

**Comment by weixingzhang** [comment]
**The below are implemented in this PR.**

1.  HIP Texture Runtime APIs
     - Texture reference APIs
cudaBindTexture   ( size_t* offset, const textureReference* texref, const void* devPtr, const   cudaChannelFormatDesc* desc, size_t size = UINT_MAX )
cudaBindTexture2D   ( size_t* offset, const textureReference* texref, const void* devPtr, const   cudaChannelFormatDesc* desc, size_t width, size_t height, size_t pitch )
cudaBindTextureToArray   ( const textureReference* texref, cudaArray_const_t array, const   cudaChannelFormatDesc* desc )
cudaCreateChannelDesc   ( int  x, int  y, int  z, int  w, cudaChannelFormatKind f   )
cudaGetChannelDesc   ( cudaChannelFormatDesc* desc, cudaArray_const_t array )
cudaUnbindTexture   ( const textureReference* texref )

      -  Texture object APIs
cudaCreateTextureObject   ( cudaTextureObject_t* pTexObject, const cudaResourceDesc* pResDesc, const   cudaTextureDesc* pTexDesc, const cudaResourceViewDesc* pResViewDesc )
cudaDestroyTextureObject   ( cudaTextureObject_t texObject )
cudaGetTextureObjectResourceDesc   ( cudaResourceDesc* pResDesc, cudaTextureObject_t texObject )
cudaGetTextureObjectResourceViewDesc   ( cudaResourceViewDesc* pResViewDesc, cudaTextureObject_t texObject )
cudaGetTextureObjectTextureDesc   ( cudaTextureDesc* pTexDesc, cudaTextureObject_t texObject )

2. HIP Texture Device Built-ins
    - Support data types: char, char1, char2, char4, unsigned char, uchar1, uchar2, uchar4, 
                                           short, short1, short2, short4, unsigned short, ushort1, ushort2, ushort4
                                           int, int1, int2, int4, unsigned int, uint1, uint2, uint4
                                           float, float1, float2, float4

    - Texture object built-ins
template<class   T> T tex1Dfetch(cudaTextureObject_t texObj, int x)
template<class   T> T tex1D(cudaTextureObject_t texObj, float x)
template<class   T> T  tex1DLod(cudaTextureObject_t texObj, float x, float level)
template<class   T> T tex1DGrad(cudaTextureObject_t texObj, float x, float dx, float dy)
template<class   T> T tex2D(cudaTextureObject_t texObj, float x, float y)
template<class   T> tex2DLod(cudaTextureObject_t texObj, float x, float y, float level)
template<class   T> T tex2DGrad(cudaTextureObject_t texObj, float x, float y, float2 dx,   float2 dy)
template<class   T> T tex3D(cudaTextureObject_t texObj, float x, float y, float z)
template<class   T> T tex3DLod(cudaTextureObject_t texObj, float x, float y, float z, float   level)
template<class   T> T tex3DGrad(cudaTextureObject_t texObj, float x, float y, float z,   float4 dx, float4 dy)
template<class   T> T tex1DLayered(cudaTextureObject_t texObj, float x, int layer)
template<class   T> T tex1DLayeredLod(cudaTextureObject_t texObj, float x, int layer, float   level)
template<class   T> T tex1DLayeredGrad(cudaTextureObject_t texObj, float x, int layer,   float dx, float dy)
template<class   T> T tex2DLayered(cudaTextureObject_t texObj, float x, float y, int layer)
template<class   T> T tex2DLayeredLod(cudaTextureObject_t texObj, float x, float y, int   layer, float level)
template<class   T> T tex2DLayeredGrad(cudaTextureObject_t texObj, float x, float y, int   layer, float2 dx, float2 dy)

- Texture reference built-ins

template<class   DataType> Type tex1Dfetch( texture<DataType, cudaTextureType1D,   cudaReadModeElementType> texRef, int x)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex1D(texture<DataType, cudaTextureType1D, readMode> texRef, float x)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex1DLod(texture<DataType, cudaTextureType1D, readMode> texRef, float   x, float level)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex1DGrad(texture<DataType, cudaTextureType1D, readMode> texRef, float   x, float dx, float dy)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex2D(texture<DataType, cudaTextureType2D, readMode> texRef, float x,   float y)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex2DLod(texture<DataType, cudaTextureType2D, readMode> texRef, float   x, float y, float level)
template<class   DataType, enum cudaTextureReadMode readMode> Type tex2DGrad(texture<DataType,   cudaTextureType2D, readMode> texRef, float x, float y, float2 dx, float2   dy)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex3D(texture<DataType, cudaTextureType3D, readMode> texRef, float x,   float y, float z)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex3DLod(texture<DataType, cudaTextureType3D, readMode> texRef, float   x, float y, float z, float level)
template<class   DataType, enum cudaTextureReadMode readMode> Type tex3DGrad(texture<DataType,   cudaTextureType3D, readMode> texRef, float x, float y, float z, float4 dx,   float4 dy)
template<class   DataType, enum cudaTextureReadMode readMode> Type tex1DLayered(   texture<DataType, cudaTextureType1DLayered, readMode> texRef, float x,   int layer)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex1DLayeredLod(texture<DataType, cudaTextureType1D, readMode> texRef,   float x, int layer, float level)
template<class   DataType, enum cudaTextureReadMode readMode> Type tex1DLayeredGrad(texture<DataType,   cudaTextureType1D, readMode> texRef, float x, int layer, float dx, float   dy)
template<class   DataType, enum cudaTextureReadMode readMode> Type tex2DLayered(   texture<DataType, cudaTextureType2DLayered, readMode> texRef, float x,   float y, int layer)
template<class   DataType, enum cudaTextureReadMode readMode> Type   tex2DLayeredLod(texture<DataType, cudaTextureType2D, readMode> texRef,   float x, float y, int layer, float level)
template<class   DataType, enum cudaTextureReadMode readMode> Type tex2DLayeredGrad(texture<DataType,   cudaTextureType2D, readMode> texRef, float x, float y, int layer, float2   dx, float2 dy)

**The below haven’t been done.**

1. CUDA Texture Driver APIs
2. CUDA Texture Runtime APIs
- Texture object API
cudaBindTextureToMipmappedArray ( const textureReference* texref, cudaMipmappedArray_const_t mipmappedArray, const cudaChannelFormatDesc* desc )

- Texture reference APIs.
cudaGetTextureAlignmentOffset   ( size_t* offset, const textureReference* texref )
cudaGetTextureReference   ( const textureReference** texref, const void* symbol )

3. CUDA Texture Device Built-ins for cubemap and gather and other data types such as long, double...

**Comment by adityaatluri** [comment]
@weixingzhang , we need dtests.

**Comment by weixingzhang** [comment]
@adityaatluri where can I put the tests? By the way, the tests what I have are derived from CUDA samples. I don't think they can be put in this repo.

**Comment by weixingzhang** [comment]
Please review this change. If there is no concerns, please merge it.

**Comment by emankov** [comment]
Weixing, there is no reviewers in your change as long as in mine ([#105](https://github.com/ROCm-Developer-Tools/HIP/pull/100)). Can you add reviewers to your pull request? I can't.

**Comment by weixingzhang** [comment]
[cuda texture tests.zip](https://github.com/ROCm-Developer-Tools/HIP/files/1165682/cuda.texture.tests.zip)

Three tests which were changed from CUDA samples/0_Simple are attached.

**Comment by weixingzhang** [comment]
@kknox What does "All checks have failed" mean in this pull request?

**Comment by weixingzhang** [comment]
@emankov How can I add reviewers? Thanks!

**Comment by emankov** [comment]
You can't as well as I can't, it looks like we have no permissions :)

**Comment by kknox** [comment]
HiP PR's are run through CI, and HiP unit tests are run.  You can click the 'Details' link, but you need to be behind the AMD firewall to see the results.
```
The following tests FAILED:
	  1 - directed_tests/hipEnvVarDriver.tst (OTHER_FAULT)
Errors while running CTest
```

I think this is a benign failure, and probably can be ignored.  @mangupta could confirm

**Comment by mangupta** [comment]
Yes. the one failing test can be ignored. I have submitted PR #109 that disables this test for CI only.

**Comment by mangupta** [comment]
@weixingzhang: As mentioned by Aditya, we definitely need some directed tests for this. And as you rightly mentioned, we cannot use the ones derived from CUDA samples.

**Pull request merged**
