### PR TITLE
Revert "Using HSA API for hipMemsetAsync"

### PR DESCRIPTION
**Pull request by gargrahul**
Reverts ROCm-Developer-Tools/HIP#1346

This implementation requires review and possible rework.

### CODE REVIEW

**Comment by emankov** [comment]
What's wrong with  #1346 was being already reviewed?

**Comment by gargrahul** [comment]
Merging this as it is solving many issues. @emankov we can discuss offline about incorrectness in #1346 .

**Comment by gargrahul** [comment]
@emankov could you approve ? I can't approve since I am submitter this revert.

**Comment by emankov** [comment]
I'd prefer seeing failed tests due to #1346, which has been merged a week ago. Could you provide the logs?

**Comment by gargrahul** [comment]
> 
> 
> I'd prefer seeing failed tests due to #1346, which has been merged a week ago. Could you provide the logs?

One problem in #1346 SEEMS that it is NOT handling int16/fp16 cases correctly. 

I agree with you however I don't have any ready logs. You can check SWDEV-201581 and SWDEV-201745. These issues are P1.

I will wait for @mangupta to approve this and merge it.

**Comment by gargrahul** [comment]
Any fix for #1346 would require a new PR anyways. #1346 was for performance improvement and fix for broken functionality is critical now.

**Comment by emankov** [comment]
Rahul, my opinion here is that as long as we all are contributing into open source, the concrete reasons for rejecting or reverting any PR should be provided. Offline discussion is not working here as well as links to issues on internal sources. Anyway, don't forget to provide those concrete reasons before reverting: they should be visible for the contributing community. Thanks.

**Comment by gargrahul** [comment]
> 
> 
> Rahul, my opinion here is that as long as we all are contributing into open source, the concrete reasons for rejecting or reverting any PR should be provided. Offline discussion is not working here as well as links to issues on internal resources. Anyway, don't forget to provide those concrete reasons before reverting: they should be visible for the contributing community. Thanks.

@emankov  I completely agree with you. We respect all contributions in HIP and thank all contributors - an important motivating factor for us.

This revert and merge is necessary to unblock other teams and manage our other critical commitments.

In my opinion, we don't have a HIP level dtest for checking all scenarios for hipMemset/hipMemsetAsync else we would have captured and fixed those in #1346 before merging it. We need to fix this gap.

**Pull request merged**
