### PR TITLE
Revert "Revert "Cmake package""

### PR DESCRIPTION
**Pull request by pfultz2**
Reverts ROCm-Developer-Tools/HIP#1860

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
I think @saadrahim and his team are aware of the math lib issues, and will try to resolve them after we merge this change.

**Comment by aaronenyeshi** [comment]
+ CC @amdkila

**Comment by mangupta** [comment]
Closing this in favor of #1918

**Comment by pfultz2** [comment]
Reopening since this issue was not fixed by #1918.

**Comment by pfultz2** [comment]
@mangupta  Can we merge this in?

**Comment by mangupta** [comment]
@pfultz2 Added it to the staging tests list. Once staging passes and there are no regressions, we can merge this in.

**Comment by mangupta** [comment]
Closing since PR #2010 has been merged.

**Pull request closed without merging**
