### PR TITLE
HACK for SWDEV-173477/SWDEV-190701

### PR DESCRIPTION
**Pull request by gargrahul**
For 2.6 relesse till we resolve SWDEV-190701 properly.

### CODE REVIEW

**Comment by gargrahul** [comment]
@whchung and @sunway513 Please review this HACK and confirm whether it is helping to resolve issue seen with TF XLA tests.

**Comment by whchung** [comment]
Based on the logs we have so far I think perhaps SWDEV-190701 is a different issue than SWDEV-173477 (the code object no longer contains 0-sized symbols), so I'm not that confident this HACK would make SWDEV-190701 go away.

**Comment by whchung** [comment]
After clarification from @kzhuravl, it seems there are 2 separate loader-related issues, and the code object dump he got was actually under another context.  So this HACK should likely prevent SWDEV-190701 from happening. Waiting for more inputs from @sunway513 .

**Comment by kzhuravl** [comment]
The code object dump from another context does not seem like a loader issue. I was able to load the said code object and retrieve info about it.

For another potential issue, please provide the code object, so I can inspect it. Thanks.

________________________________________

**Comment by sunway513** [comment]
We're not able to build the tip of HIP master branch due to the following error:
`CMake Error at /root/HIP/build/packages/hip_hcc/cmake_install.cmake:44 (file):`
`  file INSTALL cannot find "/root/HIP/build/libhiprtc.so".`
@gargrahul how can we fix that? Or can you provide us a HIP package with this PR in?

**Comment by sunway513** [comment]
Just figured out how to build the tip of HIP master branch, I have to build hiprtc before trying to build all the packages. 
With that, here's my observations:
1. The tip of HIP master branch would fail the TF XLA unit test (//tensorflow/compiler/tests:gather_test_gpu )
2. The tip of HIP master branch + this PR would pass the TF XLA unit test

Therefore, my recommendation is to merge this PR ASAP while continue triaging the defects in ROCr.

**Pull request merged**
