### PR TITLE
Add host and device targets

### PR DESCRIPTION
**Pull request by pfultz2**
This adds cmake targets for host and device to make it easier to link against the host or device version of the library.

### CODE REVIEW

**Comment by pfultz2** [comment]
> However I would like to point out that strictly speaking hip_hcc is not a host-only library.

Yes, but it still needs to be linked when using hip from only a host compiler. `hip_hcc` also includes headers from hc runtime as well which hcc is required. 

The `hip::host` is for when the user is only using the host part of the library and most likely is compiling with a host-only compiler like g++, thus it does not include hcc runtime in its usage requirements.

**Comment by mangupta** [comment]
Linking against hip::host would still require including the hcc runtime since as I mentioned libhip_hcc.so contains a GPU kernel (See https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_memory.cpp#L1522-L1551). Hence both hip::host and hip::device have a dependency on hcc runtime. There was some issue with moving this to the device library. Once that is resolved, what you said will be true. So I approve the merge as long as we documentation or comment somewhere that hip::host currently still has a dependency on hcc runtime.

**Comment by pfultz2** [comment]
Ah, so there is no way to use hip with gcc? We can document it for now until it gets fixed.

**Comment by pfultz2** [comment]
Can this be merged?

**Pull request merged**
