### PR TITLE
Use the correct library name for rocclr

### PR DESCRIPTION
**Pull request by pfultz2**

### CODE REVIEW

**Comment by mangupta** [comment]
This needs to go to internal development branch. Please resubmit there. Closing this PR.

**Comment by pfultz2** [comment]
@mangupta Which branch do I submit a PR to? And why did you close this instead of just changing the base branch?

**Comment by gargrahul** [comment]
@pfultz2 these changes are already in https://github.com/ROCm-Developer-Tools/HIP/blob/roc-3.5.x/CMakeLists.txt.

**Comment by pfultz2** [comment]
That branch doesn't build. I get this error when configuring:

```
CMake Error at tests/hit/HIT.cmake:374 (add_custom_target):
  add_custom_target cannot create target "directed_tests.gcc.hipMalloc"
  because another target with the same name already exists.  The existing
  target is a custom target created in source directory
  "/usr/local/cget/build/tmp-318339e40b0a49c99fb316685aea07e1/HIP-roc-3.5.x".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  tests/hit/HIT.cmake:452 (hit_add_files)
  tests/hit/HIT.cmake:457 (hit_add_directory_recursive)
  CMakeLists.txt:660 (hit_add_directory_recursive)
```

It seems like something is wrong with the configuring the tests.

**Comment by gargrahul** [comment]
> 
> 
> That branch doesn't build. I get this error when configuring:
> 
> ```
> CMake Error at tests/hit/HIT.cmake:374 (add_custom_target):
>   add_custom_target cannot create target "directed_tests.gcc.hipMalloc"
>   because another target with the same name already exists.  The existing
>   target is a custom target created in source directory
>   "/usr/local/cget/build/tmp-318339e40b0a49c99fb316685aea07e1/HIP-roc-3.5.x".
>   See documentation for policy CMP0002 for more details.
> Call Stack (most recent call first):
>   tests/hit/HIT.cmake:452 (hit_add_files)
>   tests/hit/HIT.cmake:457 (hit_add_directory_recursive)
>   CMakeLists.txt:660 (hit_add_directory_recursive)
> ```
> 
> It seems like something is wrong with the configuring the tests.

Are instructions available at https://github.com/ROCm-Developer-Tools/HIP/issues/2104#issuecomment-643435845 not working for you ?

**Comment by pfultz2** [comment]
> Are instructions available at #2104 (comment) not working for you ?

I am installing it with `cget install ROCm-Developer-Tools/HIP@roc-3.5.x -DHIP_PLATFORM=vdi -DHIP_COMPILER=clang`(hcc-based version work with `cget`), which uses standard cmake commands(ie `cmake -DCMAKE_PREFIX_PATH=$PREFIX ..;make;make install`) to install. If hip doesn't work with standard cmake commands then the build scripts should be fixed.

I dont pass in the build directory to rocclr since the build directory has already been deleted(if files are needed by downstream components then they should be installed). Also, `cget` takes care of setting the `CMAKE_PREFIX_PATH` so custom variables like `ROCclr_DIR` should not be necessary.

We need to be able to build hip using standard cmake(via `cget` or `CMakeGet`) so we can can move our CI to test with hip-clang instead of hcc. With this PR and this one in [rocclr](https://github.com/ROCm-Developer-Tools/ROCclr/pull/13), we can build hip-clang, although with some workarounds for the broken installation of opencl headers(hopefully this can be fixed in the future as well).

**Comment by mangupta** [comment]
@pfultz2 The master branch was used for hip-hcc runtime development. Whereas the new runtime is developed in the internal branch. Hence master branch should be treated as deprecated. As of now only the release branch is pushed to github (after the release is done). So if this change is needed, it needs to go to the internal branch.

**Pull request closed without merging**
