### PR TITLE
Add HSA functions from ROCR Runtime for HIP 6.2.0

### PR DESCRIPTION
**Pull request by matyas-streamhpc**

### CODE REVIEW

**Comment by matyas-streamhpc** [comment]
Rebased.

**Comment by matyas-streamhpc** [comment]
Waiting for ROCR Runtime fix. - done

**Review by gandryey — APPROVED** [review]

**Review by yhuiYH — APPROVED** [review]

**Comment by yhuiYH** [comment]
Need authorized people to approve and merge.  @jujiang-del @gandryey @mangupta @rakesroy

**Comment by neon60** [comment]
@matyas-streamhpc this is already on the develop branch. Can we close this?

**Comment by neon60** [comment]
It's already on the develop branch.

**Pull request closed without merging**
