### PR TITLE
HIP supported GPUs

### PR DESCRIPTION
**Pull request by neon60**
HIP supported GPUs

### CODE REVIEW

**Comment by neon60** [comment]
Here's the text:
HIP is supported on some AMD GPUs and multiple operating systems. For more information, see:
•	[Linux system requirements](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus)
•	[Microsoft Windows system requirements](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html#windows-supported-gpus)
HIP is also supported on NVIDIA GPUs, which must be CUDA-enabled. For more information about supported NVIDIA GPUs, see [GPU Compute Capability](https://developer.nvidia.com/cuda-gpus).

**Comment by neon60** [comment]
> Here's the text: HIP is supported on some AMD GPUs and multiple operating systems. For more information, see: • [Linux system requirements](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus) • [Microsoft Windows system requirements](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html#windows-supported-gpus) HIP is also supported on NVIDIA GPUs, which must be CUDA-enabled. For more information about supported NVIDIA GPUs, see [GPU Compute Capability](https://developer.nvidia.com/cuda-gpus).

@lpaoletti @randyh62 I think this sentence is not fully in alignment with the first statement: "HIP is a C++ runtime API and kernel language that lets developers create portable applications for AMD and NVIDIA GPUs from single source code."

We are duplicating the information in these sentences and first statement.:

"HIP is supported on some AMD GPUs and multiple operating systems. HIP is also supported on NVIDIA GPUs, which must be CUDA-enabled"

Added a suggestion commit:

https://github.com/ROCm/HIP/pull/3493/commits/d0100a6c0e131b32f43dc94e883ff905ddf1ecd3

**Review by lpaoletti — APPROVED** [review]
Approving your suggestion. 
Also note Randy has a change at the top of the page:
https://github.com/ROCm/HIP/pull/3492/files

**Comment by neon60** [comment]
> Approving your suggestion. Also note Randy has a change at the top of the page: https://github.com/ROCm/HIP/pull/3492/files

Merged in the PR which was mentioned to docs/develop.

**Review by lpaoletti — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
