### PR TITLE
Remove redundant declarations.

### PR DESCRIPTION
**Pull request by mhbliao**
- The revised `hip/hip_ext.h` have that declarations.

### CODE REVIEW

**Comment by mhbliao** [comment]
So far, without this patch, several libraries failed to be compiled due to that redundant declarations.

**Comment by gargrahul** [comment]
So apps would need to include hip/hip_ext.h (for now hip/hip_hcc.h) ?

**Comment by mhbliao** [comment]
they needs revising their code to remove the including of hip_hcc.h, which still works so far with deprecated warning message. If any application fails to be compiled after this, it probably includes that hip_hcc.h conditionally with HCC checking. Their needs revising as well to include hip_ext.h directly.

**Comment by mhbliao** [comment]
BTW, even if they includes hip_ext.h directly, we still have the redundant declaration issues (due to the default argument initializers) as they are defined twice for hip-clang.

**Pull request merged**
