### PR TITLE
adding hip_prof_gen verbose log

### PR DESCRIPTION
**Pull request by eshcherb**

### CODE REVIEW

**Comment by yxsamliu** [comment]
when I build HIP I got this error:
Error: not found: hipMemcpyToSymbolAsync
CMakeFiles/prof.dir/build.make:61: recipe for target '/home/yaxunl/git/hip/hip/include/hip/hcc_detail/hip_prof_str.h' failed

I am wondering what does this mean? Is this PR supposed to fix this? Thanks.

**Comment by eshcherb** [comment]
Yes, this PR makes it by default as a warning.

**Comment by eshcherb** [comment]
The error means that there is missing implementation of API hipMemcpyToSymbolAsync
The API is defined under __HIP_VDI__ macro.

**Comment by yxsamliu** [comment]
Thanks. That's a relief. Hope we can get this merged ASAP.

**Pull request merged**
