### PR TITLE
Fixing rocblas build failure

### PR DESCRIPTION
**Pull request by kknox**
with ::Bundled_code_header constructor

Disabling hipPrintfKernel test from CI

### CODE REVIEW

**Comment by scchan** [comment]
I have a pending PR (https://github.com/ROCm-Developer-Tools/HIP/pull/342) to turn off the printf test by asking hip's test to skip it but perhaps your change in the Jenkins script is a better to achieve that.  I'll close my PR.

**Comment by kknox** [comment]
@scchan 
Can you look at the build failure for build #8 hcc-ctu on this PR; I think the problem is unrelated to my PR, I'm thinking the latest hcc-ctu broke hip.

**Comment by scchan** [comment]
@kknox I wasn't able to reproduce the crash on my machine and it looks build #9 is passing

**Comment by kknox** [comment]
Thx, i'm looking into that particular machine

**Pull request merged**
