### PR TITLE
Implement hipGetSymbolAddress and hipGetSymbolSize

### PR DESCRIPTION
**Pull request by mkuron**

### CODE REVIEW

**Comment by mkuron** [comment]
@gargrahul, thanks for the comments. I have added a test case and introduced an `ihipModuleGetGlobal`. `hipMemcpy`(`To`|`From`)`Symbol`(|`Async`) were also calling `hipModuleGetGlobal`, which I have changed to the new function.

**Comment by mkuron** [comment]
@gargrahul, is there anything else you need me to do before this can be meeged?

**Comment by gargrahul** [comment]
Jenkins is failing due to build issue on NVCC path. I will try to fix that.

Otherwise LGTM, though I would like to have another test to use memcpy to/from symbol after getting symbol address. I have already tried that and can be added as a new PR.

**Comment by gargrahul** [comment]
@mangupta I think we can merge this unless you have any review comment.

**Pull request merged**
