### PR TITLE
Added new device attributes

### PR DESCRIPTION
**Pull request by ansurya**
[SWDEV-195118] Added new device attributes hipDeviceAttributeMaxPitch, hipDeviceAttributeTextureAlignment, hipDeviceAttributeKernelExecTimeout, hipDeviceAttributeCanMapHostMemory, hipDeviceAttributeEccEnabled

### CODE REVIEW

**Comment by ansurya** [comment]
> LGTM, but, please, update `CUDA_Driver_API_functions_supported_by_HIP.md ` as well, thanks.

Done.

**Comment by gargrahul** [comment]
@ansurya Just for confirmation, did you check the output of these attributes?

**Comment by ansurya** [comment]
> @ansurya Just for confirmation, did you check the output of these attributes?

Device   Attribute | NVIDIA GPU | AMD GPU(gfx803)
hipDeviceAttributeMaxPitch | 2147483647 | 2147483647
hipDeviceAttributeTextureAlignment | 512 | 0
hipDeviceAttributeKernelExecTimeout | 0 | 0
hipDeviceAttributeCanMapHostMemory | 1 | 1
hipDeviceAttributeEccEnabled | 0 | 0

**Comment by ansurya** [comment]
> > @ansurya Just for confirmation, did you check the output of these attributes?
>
Yes below is output ran on NVIDIA and AMD GPU's : 
> Device Attribute | NVIDIA GPU | AMD GPU(gfx803)
> hipDeviceAttributeMaxPitch | 2147483647 | 2147483647
> hipDeviceAttributeTextureAlignment | 512 | 0
> hipDeviceAttributeKernelExecTimeout | 0 | 0
> hipDeviceAttributeCanMapHostMemory | 1 | 1
> hipDeviceAttributeEccEnabled | 0 | 0

**Pull request merged**
