### PR TITLE
[HIP] Fix for hipArray_t failure on nvcc path

### PR DESCRIPTION
**Pull request by SarbojitAMD**
Fixes SWDEV#148407

### CODE REVIEW

**Comment by gargrahul** [comment]
We already have **typedef struct cudaArray* hipArray_const_t**. I am not sure why we added *const*.

**Comment by emankov** [comment]
> We already have typedef struct cudaArray hipArray_const_t*. I am not sure why we added const.

I'm not sure why we didn't add `const`:
```cpp
typedef struct cudaArray* hipArray_const_t;
```
like in CUDA's driver_types.h:
```cpp
typedef const struct cudaArray *cudaArray_const_t;
```
Just a typo?

**Comment by gargrahul** [comment]
So do we need both hipArray_const_t (already there) and hipArray_t (purpose of this PR)?

**Comment by emankov** [comment]
> So do we need both hipArray_const_t (already there) and hipArray_t (purpose of this PR)?
I think, yes, we need both, but we should aware, that hipArray_const_t is already used in the stack (somehow).

**Comment by Sarbojit2019** [comment]
I could see hipArray_const_t & hipArray_t used in multiple places so if we are realizing that we don't need both then we have to do cleanup where we should replace the one that we feel not required. This PR is just to make CUDA runtime and HIP runtime in sync.

In current codebase under hip/hcc_details/driver_types.h  has "typedef struct hipArray* hipArray_t;" corresponding change is missing for Cuda which this PR is addressing.

Feel free to share your thoughts

**Pull request merged**
