### PR TITLE
Feature native vector types

### PR DESCRIPTION
**Pull request by AlexVlx**
Let's try this again, this time whilst retaining the UDT nature of vector types that CUDA exposes. @Jorghi12 @wsttiger @whchung can you gents please verify this does not break your workflow?

### CODE REVIEW

**Comment by whchung** [comment]
Build error encountered in TensorFlow. Errors are like this:

```
In file included from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/channel_descriptor.h:27:0,
                 from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_texture_types.h:38,
                 from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_runtime_api.h:41,
                 from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hip_runtime_api.h:302,
                 from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hip_runtime.h:64,
                 from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hiprand/hiprand.h:24,
                 from tensorflow/stream_executor/rocm/rocm_rng.cc:16:
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_vector_types.h: In instantiation of 'struct HIP_vector_base<unsigned char, 1u>::<anonymous union>::<anonymous>':
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_vector_types.h:57:13:   required from 'union HIP_vector_base<unsigned char, 1u>::<anonymous>'
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_vector_types.h:55:9:   required from 'struct HIP_vector_base<unsigned char, 1u>'
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_vector_types.h:116:12:   required from 'struct HIP_vector_type<unsigned char, 1u>'
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_vector_types.h:607:1:   required from here
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_vector_types.h:59:68: error: request for member 'x' in 'std::declval<unsigned char>()', which is of non-class type 'unsigned char'
                     decltype(std::declval<Native_vec_>().x)>::type x;
                                                                    ^
```

**Comment by whchung** [comment]
@AlexVlx there may be a bit more needed:

```
In file included from bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hip_complex.h:29:0,
                 from ./tensorflow/stream_executor/rocm/rocm_helpers.h:27,
                 from tensorflow/stream_executor/rocm/rocm_rng.cc:21:
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:106:77: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, unsigned short)
                                                                             ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:107:75: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, signed short)
                                                                           ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:108:75: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, unsigned int)
                                                                           ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:109:73: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, signed int)
                                                                         ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:110:69: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, double)
                                                                     ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:111:76: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, unsigned long)
                                                                            ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:112:74: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, signed long)
                                                                          ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:113:81: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, unsigned long long)
                                                                                 ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:114:79: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipFloatComplex, signed long long)
                                                                               ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:125:78: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, unsigned short)
                                                                              ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:126:76: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, signed short)
                                                                            ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:127:76: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, unsigned int)
                                                                            ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:128:74: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, signed int)
                                                                          ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:129:69: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, float)
                                                                     ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:130:77: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, unsigned long)
                                                                             ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:131:75: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, signed long)
                                                                           ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:132:82: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, unsigned long long)
                                                                                  ^
bazel-out/k8-opt/genfiles/external/local_config_rocm/rocm/rocm/include/hip/hcc_detail/hip_complex.h:133:80: error: expected ';' at end of member declaration
     MAKE_COMPONENT_CONSTRUCTOR_TWO_COMPONENT(hipDoubleComplex, signed long long)
                                                                                ^
```

**Comment by whchung** [comment]
TensorFlow build based on HIP with this PR is a success.

**Comment by AlexVlx** [comment]
@whchung could you please take this for a spin in TF again, given the recent updates? Thank you.

**Comment by whchung** [comment]
Please do not merge. I haven’t got chance to valid the PR after it’s been modified. If not urgent please keep it open . I really don’t have time looking into this this week

**Comment by AlexVlx** [comment]
@mangupta I'll notify you when this has been validated thoroughly and is fit for merging. Even if @whchung gives the OK for TF, please do not merge until the aforementioned notification comes in. Thank you.

**Comment by whchung** [comment]
bump into LLVM ERROR using the very latest tip of this PR. will submit additional details later on.

**Comment by whchung** [comment]
turns out i was using incorrect HCC which doesn't have the proper backend logic for AtomicLoad. Once after switching to the right HCC commit, TensorFlow builds fine with this PR now.

**Comment by AlexVlx** [comment]
@mangupta most of the usual suspects seem fine; once we get the pyTorch greenlight this will be good to go.

**Comment by AlexVlx** [comment]
@mangupta seems pyTorch is fine as well, so whenever you feel like merging this it should be OK. Thanks.

**Comment by AlexVlx** [comment]
Thank you @mangupta; let's keep an eye out for any noise pertaining to this over the next days.

**Comment by jithunnair-amd** [comment]
PyTorch builds fine with the tip of HIP, but only after updating the ROCm stack from `http://172.27.226.104/artifactory/list/rocm-dkms-release-1.8-ubuntu/`
```
rocm-user@8c6acbc1fa3a:~/pytorch__ROCM__master__5$ hipcc --version
HIP version: 1.5.18270
HCC clang version 7.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 86791fc4961dc8ffde77bde20d7dfa5e5cbeff5e) (ssh://gerritgit/compute/ec/hcc-tot/llvm c1f9263485c0192d7af512ac2c7dd15d5082538e) (based on HCC 1.2.18223-5a607e6-86791fc-c1f9263 )
```
The HIP commit used to build HIP from source was: 277465eb97e38fcde5e753b3d612727b37cac2a6
The only hacks that I had to make for it to build were related to:
1. replacing `std::exp/log/pow` etc. functions with `::exp/log/pow` instead (because HIP doesn't seem to have device math functions working currently) 
2. replace `__forceinline__` with `inline`

**Comment by AlexVlx** [comment]
@jithunnair-amd I believe that the update is necessary for a separate issue / to address the atomic changes; you probably want to keep that on your radar if people try to mix and match.

**Comment by gargrahul** [comment]
@AlexVlx This PR is causing performance issues for philox subtest of rocrand kernel tests. Could this be usage issue in rocRAND? SWDEV-160313 is the ticket.

**Pull request merged**
