### PR TITLE
Fix bug when using older rocr naming

### PR DESCRIPTION
**Pull request by aaronenyeshi**
This change will allow HIP to run with old ROCR and new ROCR naming conventions.

### CODE REVIEW

**Comment by gargrahul** [comment]
@mangupta/ @aaronenyeshi  , is it working? I am seeing issue on system with older rocr.

**Comment by mangupta** [comment]
You need the corresponding patch from hcc as well.
-Maneesh

**Comment by gargrahul** [comment]
@mangupta, even while using old rocr and old HCC ?

**Comment by mangupta** [comment]
Combinations that should work I believe:

  *   Old rocr + old hip + old hcc
  *   Old rocr + new hip + new hcc
  *   New rocr + new hip + new hcc

**Comment by gargrahul** [comment]
I think we should make following combination working too as part of backward compatibility.

Old rocr + New hip + Old hcc

**Comment by gargrahul** [comment]
Thanks @aaronenyeshi

**Pull request merged**
