### PR TITLE
Remove -lnuma in hipcc

### PR DESCRIPTION
**Pull request by haampie**

### CODE REVIEW

**Comment by haampie** [comment]
@yxsamliu: can you take a look at this? Between 3.7 and 3.8 most references to numa got removed, except for this `-lnuma` flag. Was that intentional or should it be removed too?

**Comment by yxsamliu** [comment]
I am not directly working on HIP runtime. My impression is that HIP runtime uses numa therefore it needs to link with numa.

**Comment by haampie** [comment]
Thanks @yxsamliu. Who is the right person to ping here? I have multiple open PRs that I'd like somebody to look at

**Comment by yxsamliu** [comment]
> Thanks @yxsamliu. Who is the right person to ping here? I have multiple open PRs that I'd like somebody to look at

@gargrahul

**Comment by haampie** [comment]
Ping @gargrahul, is linking -lnuma really necessary?

**Comment by mangupta** [comment]
Closing all existing pull requests that do not target the develop branch. In case this pull request is still valid, please rebase your changes against develop branch and resubmit.

**Pull request closed without merging**
