### PR TITLE
EXSWHTEC-10 - Implement additional tests for hipIpcOpenMemHandle

### PR DESCRIPTION
**Pull request by mirza-halilcevic**
- Verify that opening the same handle in different contexts on same device causes an error
- Verify that opening the handle in the process that created it causes an error

### CODE REVIEW

**Review by chrispaquot — COMMENTED** [review]
Would it be possible to make it work on Windows too?

**Comment by mirza-halilcevic** [comment]
> Would it be possible to make it work on Windows too?

@chrispaquot The IPC APIs are only supported on Linux systems.

**Review by chrispaquot — DISMISSED** [review]

**Review by chrispaquot — DISMISSED** [review]

**Comment by mangupta** [comment]
@mirza-halilcevic : Some tests currently failing. Shared details separately.

**Comment by mirza-halilcevic** [comment]
> @mirza-halilcevic : Some tests currently failing. Shared details separately.

PR updated, you can proceed with the merge.

**Pull request merged**
