### PR TITLE
Match Occupancy APIs syntax with CUDA

### PR DESCRIPTION
**Pull request by satyanveshd**
Raising this PR after PR#1560 was reverted.
Matched the interface for cooperative groups with CUDA. This includes the templates for hipOccupancyMaxActiveBlocksPerMultiprocessor, hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags. 

hipOccupancyMaxPotentialBlockSize is not changed as there is no C equivalent API for this in CUDA. 

Also, modified the tests related to these API's according to the changes made.

### CODE REVIEW

**Comment by satyanveshd** [comment]
Updated the PR by moving occupancy dtests to tests/src/runtimeApi/occupancy directory.

**Comment by srinivamd** [comment]
Do these changes to APIs accompany update to the shared library version? 
Are these changes backward binary compatible?

**Comment by asalmanp** [comment]
@satyanveshd @mangupta  can you please finalize this PR and merge it into master branch? We need this PR merged in order to finalize the cooperative groups feature.

**Comment by gargrahul** [comment]
I changed the subject - as such these changes are not directly updating the cooperative groups APIs.

**Pull request merged**
