### PR TITLE
fixed if the kernel arguments are passed as NULL

### PR DESCRIPTION
**Pull request by satyanveshd**
Handled the case where a NULL is passed as one of the kernel arguments (instead of nullptr), as part of SWDEV-193444.

### CODE REVIEW

**Comment by mangupta** [comment]
@satyanveshd Can we also add a test that validates this?

**Comment by satyanveshd** [comment]
Added a test to validate when NULL is passed as a kernel argument.

**Comment by AlexVlx** [comment]
@mangupta can we hold off on merging this? It'd cross streams with a similar change that also mildly improves performance.

**Comment by AlexVlx** [comment]
@mangupta #1686 is the similar change I mentioned, which addresses the same issue in a slightly simpler way, amongst other things., (I nicked the unit test from here since it was better than the one I initially wrote). Perhaps you can determine the sequencing of these two?

**Comment by mangupta** [comment]
replaced by #1686.

**Pull request closed without merging**
