### PR TITLE
Fix missing decl for hip-clang

### PR DESCRIPTION
**Pull request by yxsamliu**
Add back decl for hipHccModuleLaunchKernel and hipExtModuleLaunchKernel for HIP/VDI only

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
https://github.com/ROCm-Developer-Tools/HIP/pull/1330 removed this, but HIP-Clang needs this back.

**Comment by gargrahul** [comment]
Why can't declaration in https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hip_hcc.h#L94-#L112 be used by hip-clang?

**Comment by aaronenyeshi** [comment]
It can be used if we update: https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hip_hcc.h#L26
But do we want more hcc named files? (isn't it deprecating?)

**Comment by yxsamliu** [comment]
> Why can't declaration in https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hip_hcc.h#L94-#L112 be used by hip-clang?

This file is for HCC only by its name. It is not proper to include it for HIP/VDI.

**Comment by mhbliao** [comment]
Before PR#1341 is finalized, shall we merge this first? builds of two major math libs are blocked days and through the weekend, there are concerns more issues may be hidden without successful builds.

**Comment by yxsamliu** [comment]
> Before PR#1341 is finalized, shall we merge this first? builds of two major math libs are blocked days and through the weekend, there are concerns more issues may be hidden without successful builds.

@gargrahul @mangupta Yes we need this urgently. teamcity miopen and rocblas build has been broken for long time

**Comment by gargrahul** [comment]
@yxsamliu Sure. We can merge this for now and can reverse this in #1341 when ready.

**Comment by aaronenyeshi** [comment]
HIP-Clang CI builds require this fix. Thank you

**Pull request merged**
