### PR TITLE
Adding missing __shfl overloads.

### PR DESCRIPTION
**Pull request by Jorghi12**
Added missing double overloads for __shfl operations.

### CODE REVIEW

**Comment by AlexVlx** [comment]
@Jorghi12 please don't do it like so, we are in the process of moving most of HIP to being header only. please coordinate with @aaronenyeshi who is driving this to get the overloads you are missing into the right place.

**Comment by mangupta** [comment]
FYI the PR that Alex mentioned is PR #515.

**Comment by aaronenyeshi** [comment]
Hi @Jorghi12 I've added the missing double __shfl functions in that PR https://github.com/ROCm-Developer-Tools/HIP/pull/515/commits/9ac31e0bb65029b164e40f76af4cfabf75fa1141

**Comment by mangupta** [comment]
Closing this since PR#515 now contains the changes that were required by this PR as well.

**Pull request closed without merging**
