### PR TITLE
Fix incorrect shfl_xor for Windows

### PR DESCRIPTION
**Pull request by arghdos**
copy/paste error, need __shfl_xor w/ lane_mask

### CODE REVIEW

**Comment by emankov** [comment]
Duplicate of #1923

**Comment by dmcdougall** [comment]
Hmmm.  Those two patches are not the same.  Is there a fundamental difference between `_down` and `_xor`?

**Comment by arghdos** [comment]
Good catch @dmcdougall -- @emankov, I left a review for the fix

**Comment by emankov** [comment]
2 copy-paste typos )

**Pull request merged**
