### PR TITLE
Support hipModuleLaunchKernel API if the kernelParams are not null.

### PR DESCRIPTION
**Pull request by iotamudelta**
Read the kernel argument layout from the metadata.

This enables an important PyTorch use case of this API.

While there, add some items to gitignore.

### CODE REVIEW

**Comment by iotamudelta** [comment]
@gargrahul looks like it built correctly? what am I missing?

**Comment by scchan** [comment]
@iotamudelta  This PR touches program_state and hip_module.  I'd like to let you know that we are trying to move most of the data structures and logic in program_state from the header into HIP's runtime shared library with #1077.  We are almost ready to merge #1077 so it looks like there will be a couple of minor changes needed to adapt this PR to #1077.

**Comment by mangupta** [comment]
@iotamudelta PR #1077 has been merged. Please rebase and resolve the conflicts in this PR.

**Comment by iotamudelta** [comment]
Overcome by events - #1097

**Pull request closed without merging**
