### PR TITLE
add changes to CMakeLists.txt which would fix issue #467

### PR DESCRIPTION
**Pull request by pradeepisro**

### CODE REVIEW

**Comment by pradeepisro** [comment]
What is the error with the checks? I am not getting that. When I click [details](http://hsautil.amd.com/job/ROCm-Developer-Tools/job/HIP/job/PR-468/1/display/redirect) nothing is showing up

**Comment by mangupta** [comment]
@pradeepisro Your change breaks building the target ```build_tests``` using ```make```. ```make``` does not see ```directed_tests``` as a target dependency for ```build_tests```. So none of the tests are built or run. While it is great to see your changes for getting HIP builds working with ```ninja```, you will need to ensure that the build still works with ```make```.

**Comment by mangupta** [comment]
Are you on the latest code from master branch?
hipMalloc3D on HCC platform is defined here: https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_memory.cpp#L407-L425
hipMalloc3D on NVCC platform is defined here: https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/nvcc_detail/hip_runtime_api.h#L385-L387

**Comment by pradeepisro** [comment]
now running make build_tests
error
`[15%]Building HIPCC object CMakeFiles/directed_tests.deviceLib.hipTestHalf.dir/tests/src/deviceLib/directed_tests.deviceLib.hipTestHalf_generated_hipTestHalf.cpp.o`

```
[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(82): error: invalid union member -- class "__half" has a disallowed member function

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(82): warning: variable "converter" was set but never used

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(91): error: explicit type is missing ("int" assumed)

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(92): error: identifier "nullptr" is undefined

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(96): error: identifier "kernel_hisnan" is undefined

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(106): warning: non-POD class type passed through ellipsis

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(111): warning: non-POD class type passed through ellipsis

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(127): error: explicit type is missing ("int" assumed)

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(128): error: identifier "nullptr" is undefined

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(132): error: identifier "kernel_hisinf" is undefined

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(142): warning: non-POD class type passed through ellipsis

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(147): warning: non-POD class type passed through ellipsis

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(165): error: explicit type is missing ("int" assumed)

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(187): error: identifier "nullptr" is undefined

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(210): error: identifier "__halfMath" is undefined

[HIP_SRC]/tests/src/deviceLib/hipTestHalf.cpp(218): error: identifier "__half2Math" is undefined

11 errors detected in the compilation of "/tmp/tmpxft_00003341_00000000-6_hipTestHalf.cpp1.ii".
```

**Comment by mangupta** [comment]
@pradeepisro My guess is that your tree is broken. Can you confirm that you see this issue when using ```make``` and the tip of the master branch of the HIP repo?

**Comment by pradeepisro** [comment]
@mangupta I cloned the repo and followed the commands in the tests/README.md file and I am getting the following error.

```
[ 39%] Building HIPCC object CMakeFiles/directed_tests.runtimeApi.module.hipFuncGetAttributes.dir/tests/src/directed_tests.runtimeApi.module.hipFuncGetAttributes_generated_test_common.cpp.o
[ 39%] Building HIPCC object CMakeFiles/directed_tests.runtimeApi.module.hipFuncGetAttributes.dir/tests/src/runtimeApi/module/directed_tests.runtimeApi.module.hipFuncGetAttributes_generated_hipFuncGetAttributes.cpp.o
HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(36): warning: rvalue references are a C++11 feature

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(36): error: explicit type is missing ("int" assumed)

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(36): error: reference variable "x" requires an initializer

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(36): error: expected a ";"

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(36): error: expected an expression

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(36): error: expected a ";"

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(37): error: explicit type is missing ("int" assumed)

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(37): error: reference variable "x" requires an initializer

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(37): error: expected a ";"

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(37): error: expected an expression

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(37): error: expected a ";"

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(38): error: explicit type is missing ("int" assumed)

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(38): error: reference variable "x" requires an initializer

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(38): error: expected a ";"

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(38): error: expected an expression

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(38): error: expected a ";"

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(33): warning: variable "a" was declared but never referenced

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(34): warning: variable "b" was declared but never referenced

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(44): error: identifier "hipFuncAttributes" is undefined

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(44): warning: list initialization syntax is a C++11 feature

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(46): error: explicit type is missing ("int" assumed)

HIP_SRC/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(46): error: identifier "hipFuncGetAttributes" is undefined

18 errors detected in the compilation of "/tmp/tmpxft_0000263f_00000000-6_hipFuncGetAttributes.cpp1.ii".

```

**Comment by pradeepisro** [comment]
@mangupta `hipFuncAttributes` and `hipFuncGetAttributes` not present in `nvcc/hip_runtime_api.h` that is the reason why I am getting part of the errors. I have to set HIP_NVCC_FLAGS manually to turn on c++11 standards as mentioned in the error. the error I am getting now is the following

```
HIP/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(46): error: cannot deduce "auto" type
HIP/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(46): warning: expression has no effect
HIP/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp(46): warning: expression has no effect
```
My platform is 
Nvidia Geforce 930M
CUDA version: 9.0

**Comment by pradeepisro** [comment]
I fixed that error. But the problem is why `hipFuncAttributes` in `hcc_detail/hip_runtime_api.h` has ptxVersion member?

**Comment by pradeepisro** [comment]
@mangupta, I think the bug is in `FindHip.cmake`. the statement that is
`set(verbose_output "$(VERBOSE)")`
must be
`set(verbose_output "${VERBOSE}")`

I think there should be curly braces instead of parentheses.

**Comment by mangupta** [comment]
I assume #522 replaces this PR. So can I close this?

**Pull request closed without merging**
