### PR TITLE
Corrected hipModule test and updated Code Object binary.

### PR DESCRIPTION
**Pull request by kpyzhov**

### CODE REVIEW

**Comment by mangupta** [comment]
Have a look at PR #1094. It has a cleaner implementation of the hipModule test amongst other changes. I believe this should also fix your issue.

**Comment by kpyzhov** [comment]
> Have a look at PR #1094. It has a cleaner implementation of the hipModule test amongst other changes. I believe this should also fix your issue.

No, your changes do not fix my issue.

**Comment by mangupta** [comment]
> 
> 
> > Have a look at PR #1094. It has a cleaner implementation of the hipModule test amongst other changes. I believe this should also fix your issue.
> 
> No, your changes do not fix my issue.

I am not sure what you mean. Please look at https://github.com/ROCm-Developer-Tools/HIP/pull/1094/commits/79843f3b1287fb31dabb9c0e7c0c422c98303410. The changes are mostly similar to yours. In addition, the commit also removes the generated file vcpy_kernel.code and adds support to the build system to always generate it.

**Comment by kpyzhov** [comment]
We are using different build system which uses pre-built kernel binary, so your change will break the hipModule test for us.

**Comment by mangupta** [comment]
@kpyzhov Okay. In that case please update this PR after resolving the conflicts due to submission of PR #1094.

**Pull request closed without merging**
