### PR TITLE
[hip] Remove scalar accessor's binary operator with T.

### PR DESCRIPTION
**Pull request by mhbliao**
- Otherwise, statements like
  ```
  v.x += 1;
  ```
  cause ambiguous overloaded operator resolution as `T&` implicit
  conversion is available. There's no need to provide dedicated binary
  operators with the value type, i.e. T.

### CODE REVIEW

**Comment by mhbliao** [comment]
HIP tests passed compilation with this change. rocRAND failed compilation without this patch. So far, PyTorch/Caffe2 failed compilation without this patch due tot he use of rocRAND.

**Comment by AlexVlx** [comment]
What is the actual issue you are trying to address, and is this only a hip-clang problem?

**Comment by mhbliao** [comment]
please fix the ambiguous ASAP as it fails the compilation of PyTorch.

**Comment by iotamudelta** [comment]
@mhbliao AFAIK PyTorch compiles on ROCm 2.9, ROCm 2.10 RC, roc-master.

**Comment by mhbliao** [comment]
It failed with hip-clang in TC. Please merge https://github.com/ROCm-Developer-Tools/HIP/pull/1683 ASAP.

**Pull request closed without merging**
