### PR TITLE
update samples for vega support

### PR DESCRIPTION
**Pull request by 7SK**

### CODE REVIEW

**Comment by mangupta** [comment]
closing this since PR #108 fixes by modifying hipcc.

**Comment by bensander** [comment]
Agree the hipcc mod is a better fix.

**Comment by adityaatluri** [comment]
As these samples are used as "the way to be use hip", I think we should merge these changes.

**Comment by mangupta** [comment]
@adityaatluri: I don't think making all HIP samples build fat binaries is the right way. We could change one samples to build as fatbin to demonstrate how to do it.

**Comment by bensander** [comment]
Agree

**Pull request closed without merging**
