### PR TITLE
enabled metadata parsing - not tested

### PR DESCRIPTION
**Pull request by adityaatluri**

### CODE REVIEW

**Comment by gargrahul** [comment]
This doesn't work so let us not push it. I will provide the working code in
a separate PR.

**Comment by adityaatluri** [comment]
@gargrahul do you know why?

**Comment by bensander** [comment]
@adityaaatluri @gargrahul - what is next step here?

**Comment by gargrahul** [comment]
We are waiting for meta data parser package from Alfred/ Konstantin

**Comment by bensander** [comment]
Closing for now, we can re-open when appropriate

**Pull request closed without merging**
