### PR TITLE
EXSWHTEC-9 - Implement additional tests for hipIpcCloseMemHandle

### PR DESCRIPTION
**Pull request by mirza-halilcevic**
- Verify that memory stays mapped when reference count is non zero
- Verify that memory stays mapped if handle is closed in a second process
- Verify that attempting to close handle in the process that created it causes an error.

### CODE REVIEW

**Review by chrispaquot — COMMENTED** [review]
Is it working on Windows?

**Review by chrispaquot — COMMENTED** [review]
This won't build on Windows I believe.

**Comment by mirza-halilcevic** [comment]
> This won't build on Windows I believe.

@chrispaquot You're right. We added a Linux-only guard around the tests.

**Comment by chrispaquot** [comment]
> > This won't build on Windows I believe.
> 
> @chrispaquot You're right. We added a Linux-only guard around the tests.

Can't we just remove it from the Windows build?

**Comment by mirza-halilcevic** [comment]
> > > This won't build on Windows I believe.
> > 
> > 
> > @chrispaquot You're right. We added a Linux-only guard around the tests.
> 
> Can't we just remove it from the Windows build?

The test is now removed from the Windows build. Please proceed with the review.

**Review by chrispaquot — DISMISSED** [review]

**Comment by mangupta** [comment]
@mirza-halilcevic : Some tests fail CI. Details shared separately.

**Comment by mirza-halilcevic** [comment]
> @mirza-halilcevic : Some tests fail CI. Details shared separately.

PR updated, you can proceed with the merge.

**Pull request merged**
