### PR TITLE
SWDEV-314372 - Refactor hipcc and hipconfig scripts

### PR DESCRIPTION
**Pull request by kzhuravl**
- Rename original hipcc to hipcc.pl
  - Rename original hipconfig to hipconfig.pl
  - New hipcc to invoke either hipcc.pl or hipcc.bin based on env var
  - New hipconfig to invoke either hipconfig.pl or hipconfig.bin based on env var

### CODE REVIEW

**Review by searlmc1 — DISMISSED** [review]
LGTM

**Comment by searlmc1** [comment]
LGTM; @gargrahul ?

**Comment by gargrahul** [comment]
> LGTM; @gargrahul ?

It is failing Jenkins build.

**Comment by gargrahul** [comment]
@kzhuravl  could you resolve the conflicts and update the PR?

This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
bin/hipcc
bin/hipconfig

**Comment by kzhuravl** [comment]
See newer PR: https://github.com/ROCm-Developer-Tools/HIP/pull/2476

**Pull request closed without merging**
