### PR TITLE
[hip] Added gfx803,gfx1010,gfx1012 kernel binary hipModule test.

### PR DESCRIPTION
**Pull request by AlexXAmd**
This is to address hipModule test seg fault in GFX1010.

### CODE REVIEW

**Comment by gargrahul** [comment]
@AlexXAmd Can't this be auto-generated now as discussed before in #1215 ?

**Comment by AlexXAmd** [comment]
Yes. This can be auto generated. But such mechanism does not exist yet.

**Comment by mangupta** [comment]
> 
> Yes. This can be auto generated. This default file can still cause problem...

@AlexXAmd So can we switch the build scripts to auto generate this file and modify the PR to delete this file instead?

**Comment by AlexXAmd** [comment]
Yes. I was thinking about deleting the file. I am busy with some other stuff now. So I cannot do it.

**Pull request merged**
