### PR TITLE
[HIP][doc] Populate README.md with the supported CUDA APIs links

### PR DESCRIPTION
**Pull request by emankov**

### CODE REVIEW

**Comment by emankov** [comment]
Just a gentle reminder.

**Comment by gargrahul** [comment]
@emankov Shall we redirect the links to respective github repos as well?

**Comment by emankov** [comment]
> Shall we redirect the links to respective github repos - APIs other than plain HIP, such as hipBlas etc. ?

Do you mean redirect for review?

**Comment by emankov** [comment]
Ping

**Pull request merged**
