### PR TITLE
return hipSuccess when count is zero

### PR DESCRIPTION
**Pull request by srinivamd**
Check size/count of bytes for zero count and return hipSuccess immediately. Used ihipLogStatus for return wherever allowed.

### CODE REVIEW

**Comment by srinivamd** [comment]
@emankov @gargrahul @mangupta please review this updated PR.

**Comment by psychocoderHPC** [comment]
I suggest to set the pointer for malloc operations to `nullptr` so that passing the pointer later to `hipFree` is not failing. Not sure if `hipFree` supports `nullptr` but should.

**Comment by srinivamd** [comment]
> I suggest to set the pointer for malloc operations to `nullptr` so that passing the pointer later to `hipFree` is not failing. Not sure if `hipFree` supports `nullptr` but should.

Isn't `nullptr` also returned on error/failure to malloc?
Also, wasn't sure about modifying caller's arg as a side-effect for nothing done.

**Comment by srinivamd** [comment]
@mangupta @gargrahul Could you please review and approve for merge it if it looks good?

**Pull request merged**
