### PR TITLE
Revert "HACK for SWDEV-173477"

### PR DESCRIPTION
**Pull request by whchung**
This reverts commit d941f19399e9b4f040aec5d41123e7073913cbc3.

Since relevant fixes in lower level component such as ROCR runtime and ld.lld has been introduced to ROCm master, filing this PR to remove this undesirable workaround in HIP.

Please do NOT merge the PR yet, as no HIP directed tests can cover this scenario just yet. I'd like to make a couple more local verification based on TensorFlow XLA first.

### CODE REVIEW

**Comment by whchung** [comment]
lower-level components and associated TensorFlow XLA tests have been verified by CQE team. removing [DO NOT MERGE YET] tag.

**Comment by whchung** [comment]
@gargrahul to my understanding the fix in ROCR would only be in ROCm 2.4, NOT ROCm 2.3. So could you make sure this PR does NOT get into release branch for 2.3?

**Comment by gargrahul** [comment]
@whchung we have already branched for 2.3 and will be cherry-picking very strictly into release branch, so I believe this won't get in 2.3 release.

**Comment by scchan** [comment]
2.3 hasn't been released yet so isn't it too early to revert this now?

**Comment by whchung** [comment]
@scchan Yes so that's why I asked @gargrahul to ensure this patch doesn't enter ROCm 2.3. It should be ok to have it landed onto `master` as TF CI uses stock ROCm releases whenever possible (albeit sometimes we have to deviate from it), rather than HIP `mater`.

**Comment by sunway513** [comment]
To clarify, we do need PR #981 to be landed in ROCm2.3 release package. 
Here's the expectations:
ROCm2.3: include HIP PR#981, not include PR#1004
ROCm2.4: include HIP PR#1004

**Comment by scchan** [comment]
@whchung  there are users that use HIP  `master` on ROCm `2.2` or `2.3` so it seems that reverting this patching should be cherrypick into a future `2.4` branch of HIP and then lands in `master` with the release of ROCm `2.4`.

**Comment by whchung** [comment]
@scchan I see. Then let me add `[DO NOT MERGE YET]` back. @gargrahul sorry for bring your confusion.

**Comment by gargrahul** [comment]
@whchung Is it possible to guard this change with ROCr work week (or equivalent version) ?

**Comment by gargrahul** [comment]
> 
> 
> To clarify, we do need PR #981 to be landed in ROCm2.3 release package.
> Here's the expectations:
> ROCm2.3: include HIP PR#981, not include PR#1004
> ROCm2.4: include HIP PR#1004

@sunway513 Regarding #981 in 2.3, @mangupta has already initiated the cherry-picking process. Let us follow up internally.

**Comment by whchung** [comment]
@gargrahul Looking at ROCR CMake I don't believe it has workweek feature, and its version number seem to bump relatively slow:
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/master/src/CMakeLists.txt#L76

So I think it's not possible to do the checks you proposed based on ROCR version.

**Comment by sunway513** [comment]
@gargrahul @mangupta 
We need this PR merged to roc-master ASAP. 
Could you make sure this PR would be landed on roc-master before ROCm2.4 is branched?

**Comment by whchung** [comment]
Removing "[DO NOT MERGE]" prefix per request from @sunway513

**Pull request merged**
