### PR TITLE
Update HIP build instruction docs/6.1.0

### PR DESCRIPTION
**Pull request by neon60**
Update HIP build instruction docs/6.1.0

### CODE REVIEW

**Comment by jujiang-del** [comment]
Looks good.
Please also port the fix to 6.1.1, it is expected to show up in the public release HIP documents.

**Comment by neon60** [comment]
> Looks good. Please also port the fix to 6.1.1, it is expected to show up in the public release HIP documents.

https://github.com/ROCm/HIP/pull/3489

**Review by samjwu — COMMENTED** [review]
why are instructions to build the HIPCC runtime being removed?

**Review by samjwu — APPROVED** [review]

**Comment by neon60** [comment]
@samjwu Could you merge this in?

> why are instructions to build the HIPCC runtime being removed?

"when build HIP runtime, we don't need  to build HIPCC."

**Pull request merged**
