### PR TITLE
Add Texture reference APIs headers

### PR DESCRIPTION
**Pull request by kjayapra-amd**
Adding Texture API declarations to hip_runtime_api.h 
Added APIs-
- hipTexRefGetArray
- hipTexRefGetAddressMode
- hipTexRefGetAddress

### CODE REVIEW

**Comment by emankov** [comment]
What's the point in adding declarations without definitions?

**Comment by kjayapra-amd** [comment]
Rahul is working on definitions for HCC, VDI already has the definition implemented.

**Comment by emankov** [comment]
This repo doesn't contain definitions. They should go together in a single commit, or this commit should go last.

**Comment by gargrahul** [comment]
@emankov It appears that these functions are already implemented in HIP/VDI and they are waiting for header changes.
Personally I am NOT in favor of header ONLY changes.

**Comment by gargrahul** [comment]
Closing it in favor of #1471

**Pull request closed without merging**
