### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by neon60**
Update requirements, the 6.1.2 was already updated.

### CODE REVIEW

**Review by samjwu — APPROVED** [review]
looks good

ideally I think we want to modify the .github/dependabot.yml to target this branch to have these PRs done by the bot
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch

**Comment by neon60** [comment]
> looks good
> 
> ideally I think we want to modify the .github/dependabot.yml to target this branch to have these PRs done by the bot https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch

Good idea, checking what I need to do.

**Comment by neon60** [comment]
> > looks good
> > ideally I think we want to modify the .github/dependabot.yml to target this branch to have these PRs done by the bot https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch
> 
> Good idea, checking what I need to do.

Update the target branch.

**Comment by neon60** [comment]
@samjwu Could you merge this in? Could I merge this in?

**Review by samjwu — APPROVED** [review]

**Comment by samjwu** [comment]
Feel free to merge it in when it's approved

I merged it in this time

**Pull request merged**
