### PR TITLE
Move __hip_hc_memcpy and __hip_hc_memset from device_utils.cpp to dev…

### PR DESCRIPTION
**Pull request by yxsamliu**
…ice_functions.h as inline functions

### CODE REVIEW

**Comment by yxsamliu** [comment]
@b-sumner could you please review this? Thanks.

**Comment by b-sumner** [comment]
What are the requirements for the source and destination pointers?  The current implementation assumes that the source and destination are at least 4 bytes apart.

**Comment by yxsamliu** [comment]
This should work for any distance between dst and src since it is used to implement memcpy. I will fix it.

**Comment by yxsamliu** [comment]
@b-sumner If abs(dst-src)<4, the size must be less than 4 since dst and src cannot overlap. In this case the implementation still works due to the switch statement. Is that right?

**Pull request merged**
