### PR TITLE
Implement accurate max block size in hipFuncGetAttributes()

### LINKED ISSUE #1662: hipFuncGetAttributes returns inaccurate maxThreadsPerBlock
With the HCC backend, using `hipFuncGetAttributes` on a `__global__` function does not always return an accurate upper bound of the maximum block size. Neither does it return a multiple of the warp size. As a consequence, when iterating over possible kernel parameters allowed by `attr.maxThreadsPerBlock`, I get an error:

`### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INVALID_ISA (0x100f) at file:mcwamp_hsa.cpp line:1194`

I believe this is because because the code in `hip_module.cpp` hardcodes a fixed number of registers per CU (65536), and does not distinguish between SGPR and VGPR usage of a kernel function. Instead, it should do something more sensible like in `hipOccupancyMaxPotentialBlockSize`.

### PR DESCRIPTION
**Pull request by jglaser**
This PR takes ensures that the `maxThreadsPerBlock` returned by `hipFuncGetAttributes` is both a multiple of the warp size and that the register usage of the maximum block does not exceed the number of available registers.

Currently targeting the 2.9.x branch because I based it off of that branch (see #1675). Can probably be rebased on master.

Fixes #1662

### CODE REVIEW

**Comment by jglaser** [comment]
It looks like the calculation was wrong in the first attempt, and I fixed it. however now my own tests are passing.

**Comment by mangupta** [comment]
@jglaser Thanks for the PR. Can you please rebase the PR against the master branch?

**Comment by jglaser** [comment]
@mangupta It would be great if someone could review, thanks. This will be a blocker once we enable CI for HOOMD blue w/HIP https://github.com/glotzerlab/hoomd-blue/pull/541

**Comment by jglaser** [comment]
Any progress on this?

**Pull request merged**
