### PR TITLE
SWDEV-355608 - deprecate/cleanup hipcc link flags

### PR DESCRIPTION
**Pull request by scchan**
- deprecate -use-staticlib, -use-sharedlib which no longer provide any functional values
- use --hip-link instead of specifying the HIP runtime by name when linking
- fix linker option bug in HIT test's cmake
- update build options for unit tests requiring pthread or rt

Change-Id: Ib49978773c80fb40c71dc52b050ce921943ee3e4

### CODE REVIEW

**Comment by scchan** [comment]
Rebased the patch in https://github.com/ROCm-Developer-Tools/HIP/pull/3093 and added minor updates

**Comment by gargrahul** [comment]
@scchan Please check the CI failures.

**Comment by scchan** [comment]
@gargrahul I fixed the Unit_hipEventMgpuMThreads.cc test, which should be linking explicitly to the pthread library.
I don't think the Windows test failure is related to my change though.

**Review by yxsamliu — DISMISSED** [review]
LGTM. Thanks

**Review by gargrahul — APPROVED** [review]

**Pull request merged**
