### PR TITLE
Revert "Cmake package"

### PR DESCRIPTION
**Pull request by cjatin**
Reverts ROCm-Developer-Tools/HIP#1831

### CODE REVIEW

**Comment by pfultz2** [comment]
Why is this being reverted? This fixes problems with the cmake, and it makes it consistent with hip when installed with `make install`. This shouldn't be reverted.

This also affects the onnx runtime.

**Comment by mangupta** [comment]
> Why is this being reverted? This fixes problems with the cmake, and it makes it consistent with hip when installed with `make install`. This shouldn't be reverted.
> 
> This also affects the onnx runtime.

#1831 broke builds of several components including MiOpen driver tests, RCCL and rocSPARSE. Since we need to freeze for 3.2 branching, reverting this for now to unblock builds. We will continue to investigate the impacted components to get them to work with #1831.

**Comment by pfultz2** [comment]
> #1831 broke builds of several components including MiOpen driver tests

I find that odd, since we test MIOpen using HIP from `make install` and not from `make package`, and we do not see any such issue. Where is the info about the issues found?

**Comment by gargrahul** [comment]
> 
> 
> > #1831 broke builds of several components including MiOpen driver tests
> 
> I find that odd, since we test MIOpen using HIP from `make install` and not from `make package`, and we do not see any such issue. Where is the info about the issues found?

Please check SWDEV-222155 and SWDEV-222158.

**Pull request merged**
